# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reservation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reservation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11reservation.proto\x12\x07library\"6\n\x12ReservationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x62ook_id\x18\x02 \x01(\x05\"-\n\x13ReservationResponse\x12\x16\n\x0ereservation_id\x18\x01 \x01(\x05\"+\n\x11ReturnbookRequest\x12\x16\n\x0ereservation_id\x18\x01 \x01(\x05\"-\n\x13\x44\x65leteReservRequest\x12\x16\n\x0ereservation_id\x18\x01 \x01(\x05\"\x15\n\x13GetAllReservRequest\"u\n\x13Reservation_details\x12\x16\n\x0ereservation_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x11\n\tuser_name\x18\x03 \x01(\t\x12\x0f\n\x07\x62ook_id\x18\x04 \x01(\x05\x12\x11\n\tbook_name\x18\x05 \x01(\t\"I\n\x14GetAllReservResponse\x12\x31\n\x0bReservation\x18\x01 \x03(\x0b\x32\x1c.library.Reservation_details2\xca\x02\n\x12ReservationService\x12H\n\x0bReserveBook\x12\x1b.library.ReservationRequest\x1a\x1c.library.ReservationResponse\x12\x46\n\nReturnbook\x12\x1a.library.ReturnbookRequest\x1a\x1c.library.ReservationResponse\x12O\n\x11\x44\x65leteReservation\x12\x1c.library.DeleteReservRequest\x1a\x1c.library.ReservationResponse\x12Q\n\x12GetAllReservations\x12\x1c.library.GetAllReservRequest\x1a\x1d.library.GetAllReservResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reservation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESERVATIONREQUEST']._serialized_start=30
  _globals['_RESERVATIONREQUEST']._serialized_end=84
  _globals['_RESERVATIONRESPONSE']._serialized_start=86
  _globals['_RESERVATIONRESPONSE']._serialized_end=131
  _globals['_RETURNBOOKREQUEST']._serialized_start=133
  _globals['_RETURNBOOKREQUEST']._serialized_end=176
  _globals['_DELETERESERVREQUEST']._serialized_start=178
  _globals['_DELETERESERVREQUEST']._serialized_end=223
  _globals['_GETALLRESERVREQUEST']._serialized_start=225
  _globals['_GETALLRESERVREQUEST']._serialized_end=246
  _globals['_RESERVATION_DETAILS']._serialized_start=248
  _globals['_RESERVATION_DETAILS']._serialized_end=365
  _globals['_GETALLRESERVRESPONSE']._serialized_start=367
  _globals['_GETALLRESERVRESPONSE']._serialized_end=440
  _globals['_RESERVATIONSERVICE']._serialized_start=443
  _globals['_RESERVATIONSERVICE']._serialized_end=773
# @@protoc_insertion_point(module_scope)
