# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import book_pb2 as book__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in book_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddBook = channel.unary_unary(
                '/library.BookService/AddBook',
                request_serializer=book__pb2.AddBookRequest.SerializeToString,
                response_deserializer=book__pb2.BookResponse.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/library.BookService/UpdateBook',
                request_serializer=book__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=book__pb2.BookResponse.FromString,
                _registered_method=True)
        self.DeleteBook = channel.unary_unary(
                '/library.BookService/DeleteBook',
                request_serializer=book__pb2.DeleteBookRequest.SerializeToString,
                response_deserializer=book__pb2.BookResponse.FromString,
                _registered_method=True)
        self.GetAllBooks = channel.unary_unary(
                '/library.BookService/GetAllBooks',
                request_serializer=book__pb2.GetAllBooksRequest.SerializeToString,
                response_deserializer=book__pb2.GetAllBooksResponse.FromString,
                _registered_method=True)
        self.GetBook = channel.unary_unary(
                '/library.BookService/GetBook',
                request_serializer=book__pb2.GetBookRequest.SerializeToString,
                response_deserializer=book__pb2.GetBookResponse.FromString,
                _registered_method=True)
        self.AddCategory = channel.unary_unary(
                '/library.BookService/AddCategory',
                request_serializer=book__pb2.AddCategoryRequest.SerializeToString,
                response_deserializer=book__pb2.CategoryResponse.FromString,
                _registered_method=True)
        self.UpdateCategory = channel.unary_unary(
                '/library.BookService/UpdateCategory',
                request_serializer=book__pb2.UpdateCategoryRequest.SerializeToString,
                response_deserializer=book__pb2.CategoryResponse.FromString,
                _registered_method=True)
        self.DeleteCategory = channel.unary_unary(
                '/library.BookService/DeleteCategory',
                request_serializer=book__pb2.DeleteCategoryRequest.SerializeToString,
                response_deserializer=book__pb2.CategoryResponse.FromString,
                _registered_method=True)
        self.GetAllCategories = channel.unary_unary(
                '/library.BookService/GetAllCategories',
                request_serializer=book__pb2.GetAllCategoriesRequest.SerializeToString,
                response_deserializer=book__pb2.GetAllCategoriesResponse.FromString,
                _registered_method=True)
        self.GetCategory = channel.unary_unary(
                '/library.BookService/GetCategory',
                request_serializer=book__pb2.GetCategoryRequest.SerializeToString,
                response_deserializer=book__pb2.GetCategoryResponse.FromString,
                _registered_method=True)


class BookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddBook(self, request, context):
        """for books
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCategory(self, request, context):
        """for book category
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=book__pb2.AddBookRequest.FromString,
                    response_serializer=book__pb2.BookResponse.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=book__pb2.UpdateBookRequest.FromString,
                    response_serializer=book__pb2.BookResponse.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=book__pb2.DeleteBookRequest.FromString,
                    response_serializer=book__pb2.BookResponse.SerializeToString,
            ),
            'GetAllBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBooks,
                    request_deserializer=book__pb2.GetAllBooksRequest.FromString,
                    response_serializer=book__pb2.GetAllBooksResponse.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=book__pb2.GetBookRequest.FromString,
                    response_serializer=book__pb2.GetBookResponse.SerializeToString,
            ),
            'AddCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCategory,
                    request_deserializer=book__pb2.AddCategoryRequest.FromString,
                    response_serializer=book__pb2.CategoryResponse.SerializeToString,
            ),
            'UpdateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCategory,
                    request_deserializer=book__pb2.UpdateCategoryRequest.FromString,
                    response_serializer=book__pb2.CategoryResponse.SerializeToString,
            ),
            'DeleteCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCategory,
                    request_deserializer=book__pb2.DeleteCategoryRequest.FromString,
                    response_serializer=book__pb2.CategoryResponse.SerializeToString,
            ),
            'GetAllCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCategories,
                    request_deserializer=book__pb2.GetAllCategoriesRequest.FromString,
                    response_serializer=book__pb2.GetAllCategoriesResponse.SerializeToString,
            ),
            'GetCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategory,
                    request_deserializer=book__pb2.GetCategoryRequest.FromString,
                    response_serializer=book__pb2.GetCategoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.BookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/AddBook',
            book__pb2.AddBookRequest.SerializeToString,
            book__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/UpdateBook',
            book__pb2.UpdateBookRequest.SerializeToString,
            book__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/DeleteBook',
            book__pb2.DeleteBookRequest.SerializeToString,
            book__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/GetAllBooks',
            book__pb2.GetAllBooksRequest.SerializeToString,
            book__pb2.GetAllBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/GetBook',
            book__pb2.GetBookRequest.SerializeToString,
            book__pb2.GetBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/AddCategory',
            book__pb2.AddCategoryRequest.SerializeToString,
            book__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/UpdateCategory',
            book__pb2.UpdateCategoryRequest.SerializeToString,
            book__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/DeleteCategory',
            book__pb2.DeleteCategoryRequest.SerializeToString,
            book__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/GetAllCategories',
            book__pb2.GetAllCategoriesRequest.SerializeToString,
            book__pb2.GetAllCategoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/GetCategory',
            book__pb2.GetCategoryRequest.SerializeToString,
            book__pb2.GetCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
